[package]
name = "the-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = ["api-4-3"] }

[lib]
crate-type = ["cdylib"]
